### ISSUE TITLE
Gtk.TreeStore's remove() now requires a 'ref' argument since Vala 0.17.2

### ISSUE THREAD

**Issue by ghost** [EasyRPG/Editor-GTK#17]
Binding change.

```
treestore_maptree.vala:160.15-160.18: error: Argument 1: Cannot pass value to reference or output parameter
        this.remove(iter);
                    ^^^^
```

I believe `this.remove(ref iter);` should work.
Add `#if VALA_0_16` conditional for previous version?

**Comment by Falc** [comment]
Since some distros include only even/stable versions, we should stick to them.

So this is not a problem at this moment because the current stable version is Vala 0.16. It will be fixed when switching to Vala 0.18. This bug should be marked as "delayed".
