### ISSUE TITLE
No download?

### ISSUE THREAD

**Issue by ShadowFox13** [EasyRPG/Editor-GTK#33]
What happend to the download?

**Comment by ghost** [comment]
We have an experimental Windows download in a blog post:
https://easy-rpg.org/blog/2012/11/experimental-build-of-easyrpg-editor-for-windows/

The Jenkins server with nightly builds is currently disabled, we are working on it.

**Comment by ghost** [comment]
Nightly downloads are available again from https://easy-rpg.org/jenkins/view/Editor/
