### ISSUE TITLE
Error during resizing window with loaded file

### ISSUE THREAD

**Issue by halamix2** [EasyRPG/Editor-GTK#39]
Yesterday I downloaded Editor from https://easy-rpg.org/jenkins/job/editor-gtk-windows/ (0.1.0) (win7 x64), and when I loaded sample_game and tried to resize the window, program crashed.
Resizing without loaded project works.

**Comment by ghost** [comment]
Thanks for reporting it. Looks like it crashes with specific GTK+ library versions. This was working with GTK+ 3.4. Setup was using an unstable GTK+ Windows build (3.10).

GTK+ Windows toolchain installed in the jenkins build bot will be updated to 3.6.4 soon.

**Comment by ghost** [comment]
Editor-GTK has been rebuilt with GTK+ 3.6.4 and resize with maps doesn't crash for me now. Could you verify again with latest rebuild?

**Comment by ghost** [comment]
> &lt;Halamix2&gt; It works now, thanks :)
